### ISSUE TITLE
[Bug]: Bamboo not dropping items

### ISSUE THREAD

**Issue by Zwikkry** [moddingplayground/twigs-forge#3]
### Minecraft version
1.18.2

### Forge version
40.0.52

### Mod version
Twigs Forge 1.1.4 Patch 1

### Java version
OpenJDK 17.0.1

### Issue Description
When destroying bamboo (block), they don't drop any bamboo (item), just the leaves which are added by Twigs.

**Comment by dvitski** [comment]
Fixed in 1.1.4-patch2
