### ISSUE TITLE
`ConcurrentModificationException` due to non-thread-safe code ran during `FMLCommonSetupEvent`

### ISSUE THREAD

**Issue by ChampionAsh5357** [moddingplayground/twigs-forge#5]
Looking at [`FMLCommonSetupEvent`](https://github.com/moddingplayground/twigs-forge/blob/1.18.2/src/main/java/net/moddingplayground/twigs/Twigs.java#L53-L62), the compostables map is updated. The map itself is a hashmap being updated during an asynchronous event. As such, a CME can be thrown if another mod, say for example, [Create Cafe](https://github.com/1mphuls3/CreateCafe-1.18/blob/master/src/main/java/com/Imphuls3/createcafe/CreateCafe.java#L44-L47) updates the compostables map at the same time.

The same is also true for the flammables, though you should be using `IForgeBlock#getFlammability` instead.

This can be fixed by wrapping the non-thread-safe code using `#enqueueWork` provided by the event.

This issue was reported in the following [Forge forum post](https://forums.minecraftforge.net/topic/116206-random-mod-loading-failures/#comment-513386).

**Comment by dvitski** [comment]
[1.18.2 fixed build](https://nightly.link/moddingplayground/twigs-forge/actions/artifacts/346802605.zip)

**Comment by falxie** [comment]
> [1.18.2 fixed build](https://nightly.link/moddingplayground/twigs-forge/actions/artifacts/346802605.zip)

Any chance for this to be released on CurseForge soon?

**Comment by dvitski** [comment]
Perhaps, I'll see what I can do soon 👍

**Comment by dvitski** [comment]
Released as `1.1.4-patch4+1.18.2-forge`!

**CurseForge** https://www.curseforge.com/minecraft/mc-mods/twigs/files/3968055
**Modrinth** <https://modrinth.com/mod/twigs/version/1.1.4-patch4+1.18.2-forge>
